[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
rtrs = { path = "../rtrs", features = ["track_locks", "track_borrows"]}
rtrs-drivers = { path = "../rtrs-drivers" }
heapless = "0.8.0"
