[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
rtrs = { path = "../rtrs", features = ["track_locks", "track_borrows"]}
void = { version = "1.0.2", default-features = false }
