[env]
RTRS_STORAGE_FIXED_SIZE = "32"
RTRS_LOG_META_FIXED_SIZE = "32"


[profile.dev]
opt-level = "s"
panic = 'abort'

[profile.release]
opt-level = "z"
debug-assertions = false
overflow-checks = false
panic = 'abort'
debug = true

[profile.release-lto]
inherits = "release"
lto = true

[profile.dev.package."*"]
inherits = "dev"

[profile.release.package."*"]
inherits = "release"

[profile.release-lto.package."*"]
inherits = "release-lto"